### PR TITLE
[JBEAP-15028] Add test coverage for URL.getContentType

### PR DESCRIPTION
**Pull request by mackaypeter**
issue: https://issues.jboss.org/browse/JBEAP-15028

### CODE REVIEW

**Comment by panossot** [comment]
Hello @mackaypeter .
 I think that in order the tests to be enabled under the basic category you should add in the pom of the test-configurations something like <include>org/jboss/additional/testsuite/jdkall/present/basic/**/*TestCase.java</include>
 at these places 
https://github.com/jboss-set/eap-additional-testsuite/blob/master/modules/testcases/jdkAll/Eap71x/basic/test-configurations/pom.xml#L46.

I was using this category, for basic tests about EAT, that is why it is not there. This should be done for all the server subcategories that the testcase is distributed (Eap71x, Eap71x-Proposed,etc).

**Comment by mackaypeter** [comment]
Hi @panossot,
I see, didn't realize that. If that's the case I can move it to another category if you'd prefer that. That way basic would still be dedicated to EAT testing.

**Comment by panossot** [comment]
Hello again @mackaypeter . It is fine to stay under the basic category. Let's just add the inclusion in order more tests to be added under this category in the future.

**Comment by mackaypeter** [comment]
@panossot I added the inclusions. Please have a look, thanks!

**Comment by panossot** [comment]
I am merging as the CI jobs pass.

**Pull request merged**
