### PR TITLE
Add support for perun - single test exec + fix cyclic dependency on o…

### PR DESCRIPTION
**Pull request by baranowb**
…penssl

Note that this is kind of hack. For some reason thunder and docker execution not not explode on open-ssl circular dependency - on thunder it does not seem affected(?), in local docker execution, it just ignores:
Downloading: http://download.devel.redhat.com/brewroot/repos/jb-eap-7.2-maven-build/latest/maven/org/wildfly/openssl/wildfly-openssl-macosx-x86_64/$%7Bversion.org.wildfly.openssl.wildfly-openssl-macosx-x86_64%7D/wildfly-openssl-macosx-x86_64-$%7Bversion.org.wildfly.openssl.wildfly-openssl-macosx-x86_64%7D.pom

### CODE REVIEW

**Comment by panossot** [comment]
Could it, in some way, not affect the existing builds?
For example, if -Dmacosxopenssl do the new staff, if not execute as is?

**Comment by panossot** [comment]
How this should be tested? Which are the extra opts?

**Comment by baranowb** [comment]
Any that you want to specify

**Comment by panossot** [comment]
Let's test with perun and openssl and I will merge. From EAT point of view it is fine.

**Comment by baranowb** [comment]
https://github.com/jboss-set/eap-additional-testsuite/pull/95   <-- go to

**Pull request closed without merging**
