### PR TITLE
[JBEAP-16904] Add a test case for deserialization of JSR310 classes.

### PR DESCRIPTION
**Pull request by mackaypeter**
issue: https://issues.jboss.org/browse/JBEAP-16904

### CODE REVIEW

**Comment by panossot** [comment]
Hello Peter. This is an old one (7.2.1).
Should be added to src2 as well.
Isn't it system dependent?

**Comment by panossot** [comment]
Also how is jackson-module-java8 (https://github.com/FasterXML/jackson-modules-java8/pull/87) is connected with jackson databind (that is an artifact of the server)?

**Comment by mackaypeter** [comment]
Hey @panossot, thanks for the review!
I added the test case to src2. Can you please explain what is the purpose of src2? Should all new test cases be also added to src2?

I suppose the rule is technically system dependent, but from the testing I've done, I doubt it will cause any issues. With the issue present, it took significantly longer than a second to deserialize and after the fix, it's pretty much instant.

The jackson-modules-java8 modules provide additional features to jackson-databind (e.g. support for date/time types). Both jackson-datatype-jdk8 and jackson-datatype-jsr310 are shipped as part of the server distribution.

**Comment by panossot** [comment]
Hello Peter. 
About the src and src2 there are multiple reasons. Let's make sure that every test addition is included in src2 (I will be moving them also in src).
Because there are some errors with the integration testing, let's rebase the PR (I have made some changes -addition of deps- in the repo that should allow them to pass).
Since there are two tests that are version aligned in this testcase, let's use only EapAdditionalTestsuite annotation and add the versioning there. ATTest is not needed in this case, as it is used for version tests that are different.
Also, let's modify a bit the title adding "prevention of unbounded latency converting decimals to time" -> "Add a test case for deserialization of JSR310 classes, testing the prevention of unbounded latency converting decimals to time." 
Regards

**Comment by mackaypeter** [comment]
Hi,
sorry this took so long, we were busy with 7.2.4 and I kinda forgot about it.
- rebased the original PR
- removed the ATTest annotations
- modified the commit message as you requested

Thanks!

**Comment by panossot** [comment]
Hello. Just the @ Test annotations need to be added.

**Comment by mackaypeter** [comment]
Ah, of course :disappointed:
 Sorry, done.

**Pull request merged**
