### PR TITLE
WIP: DO NOT MERGE [JBEAP-17653] Add test case for password property redacting in loggin…

### PR DESCRIPTION
**Pull request by mackaypeter**
Functional, but not quite ready to be merged yet, just wanted a CI run.

### CODE REVIEW

**Comment by mackaypeter** [comment]
Hi @panossot , there's no need to review just yet.

Also I'm wondering is there a way to annotate a class so that it's always included? In case of shared utility classes this would be nice to have.

**Comment by panossot** [comment]
About "the always inclusion annotation", it can be easily done. I will try to do it tomorrow.
But if you would like the tests to be included in these ci runs, please include them in the src2 dir, instead of src. I will add them in src afterwards.

**Comment by panossot** [comment]
On second thoughts, about "the always inclusion annotation", introduces a pb about versioning. How would we know the distributed code for different versions?

**Comment by panossot** [comment]
I think the only way is to give an option to add exclusions in cases the distribution should not be done. So, it is a dual pb. It will take some more time ...

**Comment by mackaypeter** [comment]
I don't think utility classes should care about versioning. For example the ServerLogPatternListener would be the same for all the versions. I can see how a class providin common wrappers around let's say the mgmt API would be a different case, that would need another mechanism.

Maybe just make it possible to use wildcards for the modules then? Something that would allow someone to declare this class should be always present for Eap72x and Wildfly#12.0.0, no matter the module.

**Comment by panossot** [comment]
So, you mean present for all the modules. Yes, that is possible using wildcards.

**Comment by panossot** [comment]
I will try to do it till tomorrow then ...

**Comment by panossot** [comment]
It should be done. I will update the workshop next week.

**Comment by panossot** [comment]
Closing ... Repo is differed ...

**Pull request closed without merging**
