### PR TITLE
added a test-case for RESTEASY-2300 and UNDERTOW-1614

### PR DESCRIPTION
**Pull request by istudens**
A test-case for UNDERTOW-1614 and RESTEASY-2300.

https://issues.redhat.com/browse/UNDERTOW-1614
https://issues.redhat.com/browse/RESTEASY-2300

### CODE REVIEW

**Comment by panossot** [comment]
Hello Ivo. Is there any versioning info about Wildfly and Eap? (From which versions this is applicable?)

**Comment by panossot** [comment]
Also 8080 port might be used...

**Comment by panossot** [comment]
Also could you add the sources to modules/src2 dir?

**Comment by istudens** [comment]
UNDERTOW-1614 has been merged into EAP 7.2.6, 7.3.0 and WildFly 19.0.0.Beta1.

The sources have been copied to modules/src2. Should the sources be twice there, i.e. at modules/src and modules/src2?

**Comment by panossot** [comment]
You can add it in one of them (I can take care of it afterwards)... The newer tests are usually contained also in src2 ...

**Comment by panossot** [comment]
Is there also any WFLY / JBEAP issue related?

**Comment by panossot** [comment]
Merging

**Comment by panossot** [comment]
I have merged. I will add some catch clauses though.

**Comment by panossot** [comment]
The test takes approximately one minute to run. Is it normal?

**Comment by panossot** [comment]
Also, I have changed a bit the versioning ...

**Comment by istudens** [comment]
@panossot I will take a look at the time consumption and get back to you.

**Pull request merged**
