### PR TITLE
Jmx repeat test

### PR DESCRIPTION
**Pull request by rpelisse**
@panossot As I suspected, repeating the test seems to increase its occurences of failing. Job (see [build 308](https://thunder.sin2.redhat.com/jenkins/view/EAT/job/EAT-eap-7.2.x-proposed-build/309/console) and [build 309](https://thunder.sin2.redhat.com/jenkins/view/EAT/job/EAT-eap-7.2.x-proposed-build/309/console) ). 

However, once the underlying problem resolved, I don't think it make sense to repeat this test each time, so I've made change configureable. If you opt to merge this, I would recommend, you set the property to 10 or even 20 on CCI jobs to see if the failures can also happen over there:

```
$ export OTHER_MAVEN_ARGS='-Deat.remoting.jmx.remote.memoryleak.test.repeat=15'
$ ./run-eat.sh
```

### CODE REVIEW

**Comment by panossot** [comment]
Have you tested it locally?

**Comment by rpelisse** [comment]
The reptition of the test was tested on thunder (see those 2 builds). The property I've not tested, but worst case scenario, it just does not work and the test is not repeated. 

The numerous ci-build associated with this PR are green, so I expect that, at least, I have not broken anything. 

Testing locally is a bit of pain as I need to setup a few thing for EAT to run (and I'm doing other thing).

**Comment by panossot** [comment]
I tested locally with Thread.sleep(100)
and
mvn clean install -Deap72x -Dstandalone -Deat.remoting.jmx.remote.memoryleak.test.repeat=50 -Dmodule=remoting

It works. So, it must be the gc configuration params on the servers ...

**Comment by panossot** [comment]
Also, let's not increase the time of the test by multiple repetitions.

**Comment by panossot** [comment]
-Deat.remoting.jmx.remote.memoryleak.test.repeat=100 is also successful

**Comment by rpelisse** [comment]
The idea of my change is to have a way to reproduce the problem more often, it's not a fix. With this change, you can check for sure that whatever fix you try is indeed working (avoid having the impression it works, to found out 4 build later, it does not).

The default value is 1, so no repeatition. It is very much designed to be enable for a specific build. I actually expect you to remove this for loop down the road, once the problem has been isolated and fixed (for good and for sure). 

> It works. So, it must be the gc configuration params on the servers ...

I would avoid drawing early conclusion. IMHO, I would rather try to used this and the build on thunder to play with the gc settings, see if you can make it work there and in the meantime, I would also deploy this change on CCI, see if we can or not cause a fail there.

**Comment by panossot** [comment]
Hello Romain, I have made some improvements to the test you add the repetition.
The Jmx test is out of date.

**Comment by panossot** [comment]
Also if you want to add more repeats, the more repeats the more the GCNUM should be.

**Comment by rpelisse** [comment]
Superseeded by the content of upstream.

**Comment by panossot** [comment]
For the record from https://thunder.sin2.redhat.com/jenkins/job/EAT-eap-7.2.x-proposed-build/318 (executed by Romain on 03-07-2019) :

Running org.jboss.additional.testsuite.jdkall.present.jmx.remoting.JMXRemotingMemoryLeakTestCase
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 785.341 s - in org.jboss.additional.testsuite.jdkall.present.jmx.remoting.JMXRemotingMemoryLeakTestCase
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

using  -Deat.remoting.jmx.remote.memoryleak.test.repeat=50

**Comment by panossot** [comment]
Generally, it depends on the gc.
So the GCNUM should be increasing with the repeats.

**Pull request closed without merging**
