### PR TITLE
JBEAP-18447: Implementing test case for shared sessions passivation

### PR DESCRIPTION
**Pull request by fabiobrz**
Adding test to validate that web sessions aren't passivated when `<distributable` is used.
Default HA configuration is used, i.e. <b>standalone-ha.xml</b>, default Inifinispan subsytem configuration and specifically default file store path.
The only additional configuration is represented by the `<distributable/>` element, which is added to the `web.xml` file.

To execute the test:

1. See https://github.com/jboss-set/eap-additional-testsuite/tree/master/SingleVersionTestInclusion

2. Execute Maven specifying a `standalone-ha.xml` config file:
```
$ cd SingleVersionTestInclusion/wildfly
$ mvn clean install -Djboss.server.config.file.name=standalone-ha.xml
```

See https://issues.redhat.com/browse/WFLY-12954

The test is expected to fail against EAP 7.2.5 and to succeed against Wildfly 19.0.0.Beta1.

### CODE REVIEW

**Comment by panossot** [comment]
Hello @fabiobrz. I will check this tomorrow. It just came in my attention.

**Comment by panossot** [comment]
Since this is infinispan related, I think I should create, first, an infinispan subcategory in EAT. I will probably do it tomorrow. Then I will send you the equivalent of the SingleVersion PR, so that you can do a PR for the multiversion.

**Comment by fabiobrz** [comment]
> Since this is infinispan related, I think I should create, first, an infinispan subcategory in EAT. I will probably do it tomorrow. Then I will send you the equivalent of the SingleVersion PR, so that you can do a PR for the multiversion.

Hi @panossot and thanks for your comment. I'll wait for revisited contents from you and then we'll discuss what to do.

**Comment by panossot** [comment]
You could create a multi-version PR from https://github.com/panossot/eap-additional-testsuite/commit/01a4d46af1bbae6ec333b52053f1d30a0e2f505d

**Comment by panossot** [comment]
Closing ... Repo is differed ...

**Pull request closed without merging**
